# Generated by Django 5.0 on 2024-04-04 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('Area_id', models.AutoField(primary_key=True, serialize=False)),
                ('Area_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Cafe_Table',
            fields=[
                ('Table_id', models.AutoField(primary_key=True, serialize=False)),
                ('Layout_Image', models.CharField(max_length=2000)),
                ('No_of_seats', models.IntegerField()),
                ('Avaibility_status', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'Cafe_Table',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_id', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'ContactUs',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=300)),
                ('is_admin', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField()),
                ('Area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.area')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Date', models.DateField()),
                ('Delivery_address', models.CharField(max_length=255)),
                ('Total_Amount', models.IntegerField()),
                ('Order_status', models.CharField(max_length=100)),
                ('Payment_status', models.CharField(max_length=100)),
                ('Payment_Mode', models.CharField(max_length=100)),
                ('Delivery_status', models.CharField(max_length=100)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Description', models.CharField(max_length=400)),
                ('Product_image', models.CharField(max_length=2000)),
                ('Quantity', models.IntegerField()),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('Order_Item_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.order')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.product')),
            ],
            options={
                'db_table': 'Order_Item',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=400)),
                ('Feedback_date', models.DateField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.customer')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.product')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='CartTable',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.PositiveIntegerField()),
                ('Total', models.IntegerField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.customer')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.product')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Table_booking',
            fields=[
                ('Booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('Phonenumber', models.IntegerField()),
                ('Booking_Date', models.DateField()),
                ('Booking_status', models.CharField(max_length=100)),
                ('Booking_Time', models.TimeField()),
                ('NumberofPeople', models.IntegerField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.customer')),
                ('Table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe_admin.cafe_table')),
            ],
            options={
                'db_table': 'Table_booking',
            },
        ),
    ]
